module.exports = {
  name: 'zrlong',
  name1: '自然长码',
  tableName: '零声母',
  row1: [
    { alphabet: 'U', yun1: 'á', yun2: 'ǎi', yun3: 'āng', yun4: 'ěr', yun5: 'iǎng', yun6: 'iáo', yun7: 'uǎng', yun8: 'üē' },
    { alphabet: 'I', yun1: 'à', yun2: 'è', yun3: 'ǒ', yun4: 'áo', yun5: 'ēi', yun6: 'iáng', yun7: 'üé' },
    { alphabet: 'R', yun1: 'ē', yun2: 'éi', yun3: 'òu', yun4: 'ùn', yun5: 'iān' },
    { alphabet: 'E', yun1: 'é', yun2: 'ó', yun3: 'ēn', yun4: 'īng', yun5: 'iàng', yun6: 'iǒng', yun7: 'uàng' },
    { alphabet: 'T', yun1: 'ì', yun2: 'uá', yun3: 'uī' },
    { alphabet: 'P', yun1: 'ō', yun2: 'ǎng', yun3: 'iǎn', yun4: 'iōng', yun5: 'uǎi', yun6: 'uò' },
    { alphabet: 'O', yun1: 'ài', yun2: 'ǎn', yun3: 'ěn', yun4: 'èn', yun5: 'ǔn', yun6: 'iù', yun7: 'uán', yun8: 'üě' },
    { alphabet: 'W', yun1: 'áng', yun2: 'ǐng', yun3: 'ìng', yun4: 'uāng', yun5: 'uí' },
    { alphabet: 'Q', yun1: 'āo', yun2: 'ēr', yun3: 'iè' },
    { alphabet: 'Y', yun1: 'ěng', yun2: 'òng', yun3: 'iāng' },
  ],
  row2: [
    { alphabet: 'L', yun1: 'ā', yun2: 'ě', yun3: 'ú', yun4: 'iǎo', yun5: 'iào', yun6: 'uó', yun7: 'uǒ' },
    { alphabet: 'J', yun1: 'ī', yun2: 'àn', yun3: 'ěi', yun4: 'óng' },
    { alphabet: 'G', yun1: 'ǐ', yun2: 'ò', yun3: 'ūn', yun4: 'uǎ', yun5: 'uà', yun6: 'uāi' },
    { alphabet: 'A', yun1: 'ū', yun2: 'óu', yun3: 'iàn' },
    { alphabet: 'H', yun1: 'ù', yun2: 'ǖ', yun3: 'ǚ', yun4: 'èr', yun5: 'īn' },
    { alphabet: 'F', yun1: 'ǜ', yun2: 'èi', yun3: 'éng', yun4: 'èng', yun5: 'ún', yun6: 'uài', yun7: 'uì' },
    { alphabet: 'D', yun1: 'ái', yun2: 'àng', yun3: 'iā', yun4: 'uān', yun5: 'üè' },
    { alphabet: 'K', yun1: 'án', yun2: 'ér', yun3: 'ōng', yun4: 'iē', yun5: 'ióng' },
    { alphabet: 'S', yun1: 'én', yun2: 'ié', yun3: 'uā', yun4: 'uái', yun5: 'uǎn', yun6: 'uō' },
  ],
  row3: [
    { alphabet: 'M', yun1: 'ǎ', yun2: 'ǔ', yun3: 'ǘ', yun4: 'iāo', yun5: 'iú' },
    { alphabet: 'B', yun1: 'í', yun2: 'āi', yun3: 'uáng' },
    { alphabet: 'N', yun1: 'ān', yun2: 'íng', yun3: 'ǒng', yun4: 'iǎ' },
    { alphabet: 'X', yun1: 'ǎo', yun2: 'ǐn', yun3: 'ōu', yun4: 'ià' },
    { alphabet: 'V', yun1: 'ào', yun2: 'ìn', yun3: 'ián', yun4: 'uǐ' },
    { alphabet: 'C', yun1: 'ēng', yun2: 'ín', yun3: 'iá', yun4: 'iě', yun5: 'uàn' },
    { alphabet: 'Z', yun1: 'ǒu', yun2: 'iū', yun3: 'iǔ' },
  ],
  table1: [
    { yun: 'ā', bianma: 'al' },
    { yun: 'á', bianma: 'au' },
    { yun: 'ǎ', bianma: 'am' },
    { yun: 'à', bianma: 'ai' },
    { yun: 'āi', bianma: 'ab' },
    { yun: 'ái', bianma: 'ad' },
    { yun: 'ǎi', bianma: 'au' },
    { yun: 'ài', bianma: 'ao' },
    { yun: 'āng', bianma: 'au' },
    { yun: 'áng', bianma: 'aw' },
    { yun: 'ǎng', bianma: 'ap' },
    { yun: 'àng', bianma: 'ad' },
    { yun: 'āo', bianma: 'aq' },
    { yun: 'áo', bianma: 'ai' },
    { yun: 'ǎo', bianma: 'ax' },
    { yun: 'ào', bianma: 'av' },
    { yun: 'ān', bianma: 'an' },
    { yun: 'án', bianma: 'ak' },
    { yun: 'ǎn', bianma: 'ao' },
    { yun: 'àn', bianma: 'aj' },
  ],
  table2: [
    { yun: 'ē', bianma: 'er' },
    { yun: 'é', bianma: 'ee' },
    { yun: 'ě', bianma: 'el' },
    { yun: 'è', bianma: 'ei' },
    { yun: 'ēr', bianma: 'eq' },
    { yun: 'ér', bianma: 'ek' },
    { yun: 'ěr', bianma: 'eu' },
    { yun: 'èr', bianma: 'eh' },
    { yun: 'ēi', bianma: 'ei' },
    { yun: 'éi', bianma: 'er' },
    { yun: 'ěi', bianma: 'ej' },
    { yun: 'èi', bianma: 'ef' },
    { yun: 'ēn', bianma: 'ee' },
    { yun: 'én', bianma: 'es' },
    { yun: 'ěn', bianma: 'eo' },
    { yun: 'èn', bianma: 'eo' },
    { yun: 'ēng', bianma: 'ec' },
    { yun: 'éng', bianma: 'ef' },
    { yun: 'ěng', bianma: 'ey' },
    { yun: 'èng', bianma: 'ef' },
  ],
  table3: [
    { yun: 'ō', bianma: 'op' },
    { yun: 'ó', bianma: 'oe' },
    { yun: 'ǒ', bianma: 'oi' },
    { yun: 'ò', bianma: 'og' },
    { yun: 'ōu', bianma: 'ox' },
    { yun: 'óu', bianma: 'oa' },
    { yun: 'ǒu', bianma: 'oz' },
    { yun: 'òu', bianma: 'or' },
    { yun: 'ōng', bianma: 'ok' },
    { yun: 'óng', bianma: 'oj' },
    { yun: 'ǒng', bianma: 'on' },
    { yun: 'òng', bianma: 'oy' },
  ],
  table4: [
    { yun: 'iāo', bianma: 'im' },
    { yun: 'iáo', bianma: 'iu' },
    { yun: 'iǎo', bianma: 'il' },
    { yun: 'iào', bianma: 'il' },
    { yun: 'iāng', bianma: 'iy' },
    { yun: 'iáng', bianma: 'ii' },
    { yun: 'iǎng', bianma: 'iu' },
    { yun: 'iàng', bianma: 'ie' },
    { yun: 'iū', bianma: 'iz' },
    { yun: 'iú', bianma: 'im' },
    { yun: 'iǔ', bianma: 'iz' },
    { yun: 'iù', bianma: 'io' },
    { yun: 'iān', bianma: 'ir' },
    { yun: 'ián', bianma: 'iv' },
    { yun: 'iǎn', bianma: 'ip' },
    { yun: 'iàn', bianma: 'ia' },
    { yun: 'īng', bianma: 'ie' },
    { yun: 'íng', bianma: 'in' },
    { yun: 'ǐng', bianma: 'iw' },
    { yun: 'ìng', bianma: 'iw' },
    { yun: 'iōng', bianma: 'ip' },
    { yun: 'ióng', bianma: 'ik' },
    { yun: 'iǒng', bianma: 'ie' },
    { yun: 'ī', bianma: 'ij' },
    { yun: 'í', bianma: 'ib' },
    { yun: 'ǐ', bianma: 'ig' },
    { yun: 'ì', bianma: 'it' },
    { yun: 'īn', bianma: 'ih' },
    { yun: 'ín', bianma: 'ic' },
    { yun: 'ǐn', bianma: 'ix' },
    { yun: 'ìn', bianma: 'iv' },
    { yun: 'iā', bianma: 'id' },
    { yun: 'iá', bianma: 'ic' },
    { yun: 'iǎ', bianma: 'in' },
    { yun: 'ià', bianma: 'ix' },
    { yun: 'iē', bianma: 'ik' },
    { yun: 'ié', bianma: 'is' },
    { yun: 'iě', bianma: 'ic' },
    { yun: 'iè', bianma: 'iq' },
  ],
  table5: [
    { yun: 'ū', bianma: 'ua' },
    { yun: 'ú', bianma: 'ul' },
    { yun: 'ǔ', bianma: 'um' },
    { yun: 'ù', bianma: 'uh' },
    { yun: 'uō', bianma: 'us' },
    { yun: 'uó', bianma: 'ul' },
    { yun: 'uǒ', bianma: 'ul' },
    { yun: 'uò', bianma: 'up' },
    { yun: 'uāng', bianma: 'uw' },
    { yun: 'uáng', bianma: 'ub' },
    { yun: 'uǎng', bianma: 'uu' },
    { yun: 'uàng', bianma: 'ue' },
    { yun: 'ūn', bianma: 'ug' },
    { yun: 'ún', bianma: 'uf' },
    { yun: 'ǔn', bianma: 'uo' },
    { yun: 'ùn', bianma: 'ur' },
    { yun: 'uā', bianma: 'us' },
    { yun: 'uá', bianma: 'ut' },
    { yun: 'uǎ', bianma: 'ug' },
    { yun: 'uà', bianma: 'ug' },
    { yun: 'uāi', bianma: 'ug' },
    { yun: 'uái', bianma: 'us' },
    { yun: 'uǎi', bianma: 'up' },
    { yun: 'uài', bianma: 'uf' },
    { yun: 'uī', bianma: 'ut' },
    { yun: 'uí', bianma: 'uw' },
    { yun: 'uǐ', bianma: 'uv' },
    { yun: 'uì', bianma: 'uf' },
    { yun: 'uān', bianma: 'ud' },
    { yun: 'uán', bianma: 'uo' },
    { yun: 'uǎn', bianma: 'us' },
    { yun: 'uàn', bianma: 'uc' },
  ],
  table6: [
    { yun: 'üē', bianma: 'vu' },
    { yun: 'üé', bianma: 'vi' },
    { yun: 'üě', bianma: 'vo' },
    { yun: 'üè', bianma: 'vd' },
    { yun: 'ǖ', bianma: 'vh' },
    { yun: 'ǘ', bianma: 'vm' },
    { yun: 'ǚ', bianma: 'vh' },
    { yun: 'ǜ', bianma: 'vf' },
  ],
  const: {
    name1StartX: 1622,
  },
  hant: {
    name1: '自然長碼',
    tableName: '零聲母',
  }
}
